server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      max: ${HTTP_MAX_THREADS:1000}
      max-queue-capacity: ${HTTP_MAX_QUEUE:1000}

logging:
  config: "classpath:logback-spring.xml"

spring:
  application:
    name: todoit-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        hbm2ddl: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 100
  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true
  flyway:
    enabled: true
    validate-on-migrate: true
    check-location: true
    locations: classpath:/db/todoit
    schemas: todoit
    baseline-on-migrate: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todoit}?reWriteBatchedInserts=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: ${DB_HIKARI_MIN_IDLE:1}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:10}
      auto-commit: ${DB_HIKARI_AUTO_COMMIT:true}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:30000}
  task:
    execution:
      pool:
        allow-core-thread-timeout: ${EXECUTION_POOL_ALLOW_TIMEOUT:true}
        core-size: ${EXECUTION_POOL_CORE_SIZE:100}
        max-size: ${EXECUTION_POOL_MAX_SIZE:500}
        keep-alive: ${EXECUTION_POOL_KEEP_ALIVE:60s}
        queue-capacity: ${EXECUTION_POOL_QUEUE_CAPACITY:500}
    scheduling:
      pool:
        size: ${SCHEDULING_POOL_SIZE:20}

springdoc:
  swagger-ui:
    # Sort docs in alpha order
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    supportedSubmitMethods: ${SWAGGER_OPERATIONS:"get", "post"} # Ограничеваем API из Swagger
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}
  override-with-generic-response: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, log
  server:
    port: ${MANAGEMENT_SERVER_PORT:88}
